# Generated by Django 3.0.5 on 2023-04-28 23:59

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Calle', models.CharField(max_length=150)),
                ('Numero', models.IntegerField()),
                ('Mts', models.CharField(max_length=50)),
                ('Propietario', models.CharField(max_length=50)),
                ('Telefono_Propietario', models.CharField(max_length=50)),
                ('Nombre_Residente', models.CharField(max_length=50)),
                ('Telefono_contacto', models.CharField(max_length=50)),
                ('Status', models.IntegerField(blank=True, choices=[(1, 'casa'), (2, 'No-casa')], default=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
