# Generated by Django 3.0.5 on 2023-04-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20230428_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Status',
            field=models.IntegerField(blank=True, choices=[(1, 'En Renta'), (2, 'En venta')], default=1),
        ),
    ]
