# Generated by Django 3.0.5 on 2023-05-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20230501_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='area',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
