# Generated by Django 3.0.5 on 2023-05-02 00:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_person_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('marca', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('placas', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Person', verbose_name='Casa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
