# Generated by Django 3.0.5 on 2023-05-02 01:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_carros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_comun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apertura', models.TimeField()),
                ('cierre', models.TimeField()),
                ('icono', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Areas comunes',
                'verbose_name_plural': 'Area comun',
            },
        ),
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('servicio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Provedor',
                'verbose_name_plural': 'Provedores',
            },
        ),
        migrations.AlterModelOptions(
            name='carros',
            options={'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Dia', models.DateField()),
                ('motivo', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Area_comun', verbose_name='Area')),
                ('casa', models.ForeignKey(limit_choices_to={'bloqueo': False}, on_delete=django.db.models.deletion.CASCADE, to='persona.Person')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Pagos_pendientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('concepto', models.IntegerField(choices=[(1, 'Cuotas'), (2, 'Penalizacion'), (3, 'Multas'), (4, 'otros')], default=1)),
                ('recargo', models.IntegerField()),
                ('estatus', models.IntegerField(choices=[(1, 'Recargo'), (2, 'Pagado'), (4, 'otros')], default=1)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.Person', verbose_name='Casa')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('Monto', models.CharField(blank=True, max_length=500)),
                ('fecha_limite', models.DateField()),
                ('concepto', models.CharField(max_length=150)),
                ('cuenta_de_pago', models.CharField(max_length=150)),
                ('forma_de_pago', models.IntegerField(choices=[(1, 'En Renta'), (2, 'En venta')], default=1)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.Provedor', verbose_name='Provedor')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
