# Generated by Django 3.0.5 on 2023-05-02 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_auto_20230501_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagos_pendientes',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
    ]
