# Generated by Django 3.0.5 on 2023-05-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_auto_20230501_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='forma_de_pago',
            field=models.IntegerField(choices=[(1, 'efectivo'), (2, 'Tarjeta')], default=1),
        ),
    ]
