# Generated by Django 3.0.5 on 2023-05-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_auto_20230501_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos_pendientes',
            name='nombre',
            field=models.CharField(default='hola', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagos_pendientes',
            name='concepto',
            field=models.IntegerField(choices=[(1, 'Cuotas'), (2, 'Penalizacion'), (3, 'Multas'), (4, 'otros'), (5, 'pendiente')], default=5),
        ),
    ]
