# Generated by Django 3.0.5 on 2023-05-02 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_auto_20230501_1935'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('area', 'casa')},
        ),
    ]
