# Generated by Django 3.0.5 on 2023-05-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0011_auto_20230501_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos_pendientes',
            name='casa',
        ),
        migrations.AddField(
            model_name='person',
            name='pagos',
            field=models.ManyToManyField(to='persona.Pagos_pendientes'),
        ),
        migrations.AlterField(
            model_name='pagos_pendientes',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'No pagado'), (2, 'Pagado'), (4, 'otros')], default=1),
        ),
    ]
